apiVersion: v1
kind: Service
metadata:
  name: producer-bilira
  namespace: bilira
spec:
  selector:
    app: producer-bilira
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
  clusterIP: None
