apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: bilira
data:
  KAFKA_BROKER: kafka-0.kafka-headless.kafka.svc.cluster.local:9092
  KAFKA_TOPIC: event
  MONGO_URI: mongodb://root:123456@mongodb.mongodb.svc.cluster.local:27017/kafka-db
  LISTENER_PORT: "3000"
