apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmcharts.fullname" . }}-consumer-bilira
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumerBilira.replicas }}
  selector:
    matchLabels:
      app: consumer-bilira
    {{- include "helmcharts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: consumer-bilira
      {{- include "helmcharts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "helmcharts.fullname" . }}-shared-config
        image: {{ .Values.consumerBilira.consumerBilira.image.repository }}:{{ .Values.consumerBilira.consumerBilira.image.tag
          | default .Chart.AppVersion }}
        name: consumer-bilira
        ports:
        - containerPort: 3000
        resources: {{- toYaml .Values.consumerBilira.consumerBilira.resources | nindent
          10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmcharts.fullname" . }}-consumer-bilira
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.consumerBilira.type }}
  selector:
    app: consumer-bilira
    {{- include "helmcharts.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.consumerBilira.ports | toYaml | nindent 2 }}