apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmcharts.fullname" . }}-producer-bilira
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.producerBilira.replicas }}
  selector:
    matchLabels:
      app: producer-bilira
    {{- include "helmcharts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: producer-bilira
      {{- include "helmcharts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "helmcharts.fullname" . }}-shared-config
        image: {{ .Values.producerBilira.producerBilira.image.repository }}:{{ .Values.producerBilira.producerBilira.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.producerBilira.producerBilira.imagePullPolicy }}
        name: producer-bilira
        ports:
        - containerPort: 3500
        resources: {{- toYaml .Values.producerBilira.producerBilira.resources | nindent
          10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmcharts.fullname" . }}-producer-bilira
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.producerBilira.type }}
  selector:
    app: producer-bilira
    {{- include "helmcharts.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.producerBilira.ports | toYaml | nindent 2 }}