apiVersion: v1
kind: Service
metadata:
  name: consumer-bilira
  namespace: bilira
spec:
  selector:
    app: consumer-bilira
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 
  clusterIP: None  
